name: CI Pipeline

on:
    push:
        branches: [ master ]
    pull_request:

jobs:

    build-macos:
        name: Build macOS
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: ./.github/actions/build
                with:
                    repack_os: darwin
                    compile_os: macos
                    php: 8.3

    build-linux:
        name: Build Linux
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: ./.github/actions/build
                with:
                    repack_os: linux
                    compile_os: linux
                    php: 8.3

    create-plugin:
        name: Create plugin and install it
        runs-on: ubuntu-latest
        needs: [build-linux]
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3
                    extensions: gd, intl, json
                    ini-values: date.timezone=UTC
                    tools: symfony-cli
            -   name: Download binary
                uses: actions/download-artifact@v2
                with:
                    name: plugin-maker.linux
                    path: ./
            -   name: Create a plugin
                run: SyliusPluginMaker/plugin-maker.linux create --no-interaction "Sylius Bazinga Plugin"
                shell: bash
            -   name: Install the plugin
                working-directory: ./SyliusBazingaPlugin
                run: make install

    release-artifacts:
        name: Release artifacts
        runs-on: ubuntu-latest
        needs: [build-macos, build-linux, create-plugin]
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v2
                with:
                    path: ./artifacts
            -   name: Upload files to the release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        ./artifacts/plugin-maker.linux
                        ./artifacts/plugin-maker.linux.phar
                        ./artifacts/plugin-maker.darwin
                        ./artifacts/plugin-maker.darwin.phar
